#cloud-config
#
# Set Hostname
hostname: CoreBM#

# Set SSH Key
ssh_authorized_keys:
 - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDr5u9kTLUw6my4E/vFmSty0Q86SyLF8e2u7+prJg/U6/1Ps5oWgCZNOUDeZIkuZtN91TisiuTszgCv8lJUEPFyWKsfAwrzzyez4LvPMyiRgjJlVCYvjt2dZUrOM7FaPKVoM8n3zreeqkG38McHo0ocrACiX/KuiuTGAFt9G4Kq1SMWz973TTXJKoI+pbWrDK/BiD+lDTkqB/yhuFHAVJ8ZPUrHDv4+/o8/9ihm1GtSCUP1t87xfnO/ID0PGb6F3Ki+s6H7ByVjxXJYYliNgpKr8BM+mRpXenMfaltEcKuDKAjJEFJ9wBTkVtJsmo9JbO91Xbku7pFuFOaN6HA2Ppxd rihard@rihard-nb"

coreos:
  etcd2:
    discovery: https://discovery.etcd.io/14b530f2f2b0f542996f68cdc35ce649

  units:
    - name: etcd2.service
      command: start
